/**
 * Data Management & Production Reset Service
 * Enables resetting all dummy/mock data and transitioning ApniSociety to 
 * Real Production Data mode with clean slates, real member onboarding, and zeroed ledgers.
 */

import { getActiveSocietyId, getSocietyConfig } from './societyConfig';
import { SocietyConfig, SocietyItem } from '../types/societyConfig';
import { CommitteeRole, SocietyMember, SocietyUnit } from '../types/members';
import { MaintenanceBill } from '../types/maintenance';
import { ComplaintTicket } from '../types/complaints';
import { SocietyExpense, ReimbursementClaim } from '../types/expenses';
import { WaterMeterReading } from '../types/water';
import { HallBooking } from '../types/hallBooking';
import { SocietyNotification } from '../types/notifications';
import { syncNewSocietyToFirestore } from './firebase';

// Canonical Storage Keys
export const STORAGE_KEYS = {
  DATA_MODE: 'apnisociety_data_mode',
  MEMBERS: 'apnisociety_members_data',
  STAFF: 'apnisociety_staff_data',
  UNITS: 'apnisociety_units_data',
  BILLS: 'apnisociety_maintenance_bills',
  COMPLAINTS: 'apnisociety_complaints_v1',
  EXPENSES: 'apnisociety_expenses_data',
  CLAIMS: 'apnisociety_reimbursement_claims',
  DETAILED_CLAIMS: 'apnisociety_detailed_claims_v1',
  WATER_READINGS: 'apnisociety_water_readings',
  WATER_TARIFF: 'apnisociety_water_tariff',
  BOOKINGS: 'apnisociety_hall_bookings_v1',
  NOTIFICATIONS: 'apnisociety_notifications_v1',
  DEFAULTERS: 'apnisociety_defaulters_data',
  ROLES: 'apnisociety_roles_data',
  AUDIT_LOGS: 'apnisociety_roles_audit_data',
  USER_SESSION: 'apnisociety_user_session',
} as const;

export const DATA_RESET_EVENT = 'apnisociety_data_reset';

export type DataMode = 'real' | 'demo';

/**
 * Returns a storage key partitioned by society ID.
 * If targetSocietyId is 'soc-01' and not in explicit clean real mode, returns the baseKey for legacy compatibility.
 * For all new or custom societies, keys are strictly partitioned to ensure zero cross-contamination.
 */
export function getSocietyStorageKey(baseKey: string, targetSocietyId?: string): string {
  const currentId = targetSocietyId || (typeof window !== 'undefined' ? getActiveSocietyId() : 'soc-01');
  if (currentId === 'soc-01' && !isRealDataMode()) {
    return baseKey;
  }
  return `${baseKey}_${currentId}`;
}

/**
 * Check if the specified or active society is configured as clean production data (no mock/demo seed).
 * Any newly created society is clean by default: its database is created without mock data,
 * and all operational entries will be generated by the society committee.
 */
export function isSocietyCleanData(targetSocietyId?: string): boolean {
  if (typeof window === 'undefined') return false;
  const currentId = targetSocietyId || getActiveSocietyId();
  if (localStorage.getItem(STORAGE_KEYS.DATA_MODE) === 'real') return true;
  // If not the legacy demo society soc-01, it is a custom created society and starts completely clean
  if (currentId !== 'soc-01') return true;
  try {
    const raw = localStorage.getItem(`apnisociety_custom_config_${currentId}`);
    if (raw) {
      const cfg = JSON.parse(raw);
      if (cfg.isCleanProduction || cfg.withoutMockData) return true;
    }
  } catch {}
  return false;
}

/**
 * Check if the application is running in Real Production Data mode
 */
export function isRealDataMode(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(STORAGE_KEYS.DATA_MODE) === 'real';
}

/**
 * Set the current data mode ('real' for clean production, 'demo' for pre-seeded test data)
 */
export function setDataMode(mode: DataMode): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEYS.DATA_MODE, mode);
  window.dispatchEvent(new CustomEvent(DATA_RESET_EVENT, { detail: { mode } }));
}

export interface StorageStatistics {
  mode: DataMode;
  membersCount: number;
  unitsCount: number;
  billsCount: number;
  complaintsCount: number;
  expensesCount: number;
  claimsCount: number;
  waterReadingsCount: number;
  bookingsCount: number;
  notificationsCount: number;
  staffCount: number;
  isCompletelyClean: boolean;
}

/**
 * Returns summary counts of stored records across all modules for the active or target society
 */
export function getStorageStatistics(targetSocietyId?: string): StorageStatistics {
  if (typeof window === 'undefined') {
    return {
      mode: 'demo',
      membersCount: 0,
      unitsCount: 0,
      billsCount: 0,
      complaintsCount: 0,
      expensesCount: 0,
      claimsCount: 0,
      waterReadingsCount: 0,
      bookingsCount: 0,
      notificationsCount: 0,
      staffCount: 0,
      isCompletelyClean: true,
    };
  }

  const currentId = targetSocietyId || getActiveSocietyId();
  const isClean = isSocietyCleanData(currentId);

  const parseCount = (baseKey: string): number => {
    try {
      const societyKey = getSocietyStorageKey(baseKey, currentId);
      const raw = localStorage.getItem(societyKey);
      if (raw !== null) {
        const parsed = JSON.parse(raw);
        return Array.isArray(parsed) ? parsed.length : 0;
      }
      if (isClean) return 0;
      // In demo mode for soc-01, fallback to raw base key
      const fallbackRaw = localStorage.getItem(baseKey);
      if (fallbackRaw) {
        const parsed = JSON.parse(fallbackRaw);
        return Array.isArray(parsed) ? parsed.length : 0;
      }
      return 0;
    } catch {
      return 0;
    }
  };

  const mode: DataMode = isClean ? 'real' : 'demo';
  const membersCount = parseCount(STORAGE_KEYS.MEMBERS);
  const unitsCount = parseCount(STORAGE_KEYS.UNITS);
  const billsCount = parseCount(STORAGE_KEYS.BILLS);
  const complaintsCount = parseCount(STORAGE_KEYS.COMPLAINTS);
  const expensesCount = parseCount(STORAGE_KEYS.EXPENSES);
  const claimsCount = parseCount(STORAGE_KEYS.DETAILED_CLAIMS) || parseCount(STORAGE_KEYS.CLAIMS);
  const waterReadingsCount = parseCount(STORAGE_KEYS.WATER_READINGS);
  const bookingsCount = parseCount(STORAGE_KEYS.BOOKINGS);
  const notificationsCount = parseCount(STORAGE_KEYS.NOTIFICATIONS);
  const staffCount = parseCount(STORAGE_KEYS.STAFF);

  const isCompletelyClean =
    billsCount === 0 &&
    complaintsCount === 0 &&
    expensesCount === 0 &&
    waterReadingsCount === 0 &&
    bookingsCount === 0;

  return {
    mode,
    membersCount,
    unitsCount,
    billsCount,
    complaintsCount,
    expensesCount,
    claimsCount,
    waterReadingsCount,
    bookingsCount,
    notificationsCount,
    staffCount,
    isCompletelyClean,
  };
}

/**
 * Initializes a brand new Society database WITHOUT mock/dummy data.
 * When a new society is registered, all operational records (bills, complaints, expenses,
 * water readings, bookings, staff) start completely empty. All entries will be created
 * and governed by the Society Committee.
 */
export function initNewSocietyDatabase(
  society: SocietyItem,
  config: SocietyConfig,
  presidentUser: any
): {
  unitsCount: number;
  membersCount: number;
} {
  if (typeof window === 'undefined') return { unitsCount: 0, membersCount: 0 };
  const societyId = society.id;

  // 1. Generate clean real units matching configured towers
  const realUnits = generateRealSocietyUnits(config);
  const firstUnit = realUnits[0];
  if (firstUnit) {
    firstUnit.ownerName = presidentUser.name;
    firstUnit.ownerContact = presidentUser.phone;
    firstUnit.primaryResidentName = presidentUser.name;
    firstUnit.occupancyStatus = 'owner_occupied';
    firstUnit.flatNumber = presidentUser.flatNumber || firstUnit.flatNumber;
  }
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.UNITS, societyId), JSON.stringify(realUnits));

  // 2. Onboard President as the primary verified Committee Member
  const presidentMember: SocietyMember = {
    id: presidentUser.id,
    name: presidentUser.name,
    email: presidentUser.email,
    phone: presidentUser.phone,
    flatNumber: presidentUser.flatNumber || (firstUnit ? firstUnit.flatNumber : 'A-101'),
    block: presidentUser.block || (firstUnit ? firstUnit.block : 'Tower A'),
    intercomNumber: '1001',
    parkingSlots: ['P-01'],
    residentType: 'committee',
    isCommitteeMember: true,
    committeeRole: 'president',
    committeeRoleTitle: `President (${society.name})`,
    committeeBio: `President & Lead Administrator of ${society.name} Management Committee.`,
    committeePriorityOrder: 1,
    moveInDate: new Date().toISOString().split('T')[0],
    vehicles: [],
    familyMembers: [],
    hasPets: false,
    emergencyContact: {
      name: 'RWA Emergency Desk',
      relation: 'Management Office',
      phone: presidentUser.phone,
    },
    verificationStatus: 'verified',
  };
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.MEMBERS, societyId), JSON.stringify([presidentMember]));

  // 3. Initialize ALL operational tables as COMPLETELY EMPTY (NO MOCK DATA)
  // All entries will be created by the society committee!
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.BILLS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.COMPLAINTS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.EXPENSES, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.CLAIMS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.DETAILED_CLAIMS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.WATER_READINGS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.BOOKINGS, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.STAFF, societyId), JSON.stringify([]));
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.DEFAULTERS, societyId), JSON.stringify([]));

  // 4. Initial clean welcome notice from Management Committee
  const welcomeNotification: SocietyNotification = {
    id: `notif-welcome-${societyId}`,
    title: `🎉 Welcome to ${society.name} Portal`,
    message: `The database for ${society.name} is initialized without sample data. All resident registrations, maintenance invoices, vendor expenses, water readings, and clubhouse bookings will be managed directly by the Society Committee.`,
    category: 'society_notice',
    urgency: 'normal',
    channels: ['in_app', 'push_banner'],
    targetAudience: 'all_residents',
    targetLabel: 'All Residents',
    senderId: presidentUser.id,
    senderName: presidentUser.name,
    senderRole: 'President',
    createdAt: new Date().toISOString(),
    readBy: [],
    isRead: false,
    requiresAcknowledgement: false,
    acknowledgedBy: [],
  };
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.NOTIFICATIONS, societyId), JSON.stringify([welcomeNotification]));

  // 5. Initial Clean Audit Log
  const initialAuditLog = [
    {
      id: `audit-init-${societyId}`,
      action: 'SOCIETY_DATABASE_INITIALIZED',
      performedBy: presidentUser.name,
      performedByRole: 'President',
      timestamp: new Date().toISOString(),
      details: `Database created for ${society.name} without sample data. Generated ${realUnits.length} vacant units. Ready for Society Committee governance.`,
      targetId: societyId,
    },
  ];
  localStorage.setItem(getSocietyStorageKey(STORAGE_KEYS.AUDIT_LOGS, societyId), JSON.stringify(initialAuditLog));

  // 6. Set credentials for President login
  try {
    const credsRaw = localStorage.getItem('apnisociety_user_credentials');
    const creds = credsRaw ? JSON.parse(credsRaw) : {};
    creds[presidentUser.id] = 'President@123';
    creds[presidentUser.email] = 'President@123';
    creds[presidentUser.phone] = 'President@123';
    localStorage.setItem('apnisociety_user_credentials', JSON.stringify(creds));
  } catch {}

  // 7. Dispatch event
  window.dispatchEvent(new CustomEvent(DATA_RESET_EVENT, { detail: { societyId, mode: 'real' } }));

  // 8. Sync to Firestore in background
  syncNewSocietyToFirestore(society, presidentUser, welcomeNotification).catch((err) => {
    console.warn('Background Firestore sync info:', err);
  });

  return {
    unitsCount: realUnits.length,
    membersCount: 1,
  };
}

export interface ResetOptions {
  adminName?: string;
  adminEmail?: string;
  adminPhone?: string;
  adminFlat?: string;
  societyName?: string;
  generateRealUnitsFromTowers?: boolean;
}

/**
 * Generate real society units based on configured towers and wings
 */
export function generateRealSocietyUnits(config: SocietyConfig): SocietyUnit[] {
  const units: SocietyUnit[] = [];
  let unitIndex = 1;

  for (const tower of config.towers) {
    if (!tower.active) continue;
    for (let floor = 1; floor <= tower.floorsCount; floor++) {
      for (let flatNum = 1; flatNum <= tower.flatsPerFloor; flatNum++) {
        // Flat number format e.g. "A-101", "B-402"
        const flatStr = `${tower.unitPrefix}${floor}${flatNum < 10 ? '0' + flatNum : flatNum}`;
        units.push({
          id: `unit-real-${unitIndex++}`,
          flatNumber: flatStr,
          block: tower.name,
          floor: floor,
          areaSqFt: 1050,
          occupancyStatus: 'vacant',
          parkingSlots: [],
          maintenanceDueAmount: 0,
        });
      }
    }
  }

  return units;
}

/**
 * Master Reset: Purges all dummy data across all modules and establishes clean Real Data mode
 */
export function resetAllToRealProduction(options?: ResetOptions): {
  success: boolean;
  message: string;
  generatedUnits: number;
} {
  if (typeof window === 'undefined') {
    return { success: false, message: 'Window not available', generatedUnits: 0 };
  }

  const config = getSocietyConfig();
  const societyTitle = options?.societyName || config.societyName || 'ApniSociety';

  // 1. Activate Real Data Mode
  localStorage.setItem(STORAGE_KEYS.DATA_MODE, 'real');

  // 2. Clear Operational Ledgers & Dummy Activity
  localStorage.setItem(STORAGE_KEYS.BILLS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.COMPLAINTS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.EXPENSES, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.CLAIMS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.DETAILED_CLAIMS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.WATER_READINGS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.BOOKINGS, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.STAFF, JSON.stringify([]));
  localStorage.setItem(STORAGE_KEYS.DEFAULTERS, JSON.stringify([]));

  // 3. Setup Clean Real Units Architecture
  let realUnits: SocietyUnit[] = [];
  if (options?.generateRealUnitsFromTowers !== false) {
    realUnits = generateRealSocietyUnits(config);
    localStorage.setItem(STORAGE_KEYS.UNITS, JSON.stringify(realUnits));
  } else {
    localStorage.setItem(STORAGE_KEYS.UNITS, JSON.stringify([]));
  }

  // 4. Setup Initial Real Administrator Member
  let activeSessionUser: any = null;
  try {
    const rawSession = localStorage.getItem(STORAGE_KEYS.USER_SESSION);
    if (rawSession) activeSessionUser = JSON.parse(rawSession);
  } catch {}

  const adminName = options?.adminName || activeSessionUser?.name || 'Society Administrator';
  const adminEmail = options?.adminEmail || activeSessionUser?.email || 'admin@society.org';
  const adminPhone = options?.adminPhone || activeSessionUser?.phone || '9876543210';
  const adminFlat = options?.adminFlat || activeSessionUser?.flatNumber || (realUnits.length > 0 ? realUnits[0].flatNumber : 'A-101');

  const primaryAdminMember: SocietyMember = {
    id: activeSessionUser?.id || 'real-admin-001',
    name: adminName,
    email: adminEmail,
    phone: adminPhone,
    flatNumber: adminFlat,
    block: realUnits.length > 0 ? realUnits[0].block : (config.towers[0]?.name || 'Tower A'),
    intercomNumber: '1001',
    parkingSlots: ['P-01'],
    residentType: 'committee',
    isCommitteeMember: true,
    committeeRole: 'general_secretary',
    committeeRoleTitle: 'General Secretary',
    committeeBio: 'General Secretary of the Management Committee',
    moveInDate: new Date().toISOString().split('T')[0],
    vehicles: [],
    familyMembers: [],
    hasPets: false,
    emergencyContact: {
      name: 'Emergency Desk',
      relation: 'Office',
      phone: adminPhone,
    },
    verificationStatus: 'verified',
  };

  // Associate unit with admin if units exist
  if (realUnits.length > 0) {
    const firstUnit = realUnits[0];
    firstUnit.ownerName = adminName;
    firstUnit.ownerContact = adminPhone;
    firstUnit.primaryResidentName = adminName;
    firstUnit.occupancyStatus = 'owner_occupied';
    localStorage.setItem(STORAGE_KEYS.UNITS, JSON.stringify(realUnits));
  }

  localStorage.setItem(STORAGE_KEYS.MEMBERS, JSON.stringify([primaryAdminMember]));

  // 5. Initial Clean Real Notification
  const welcomeNotification: SocietyNotification = {
    id: `notif-prod-welcome-${Date.now()}`,
    title: `🎉 Welcome to ${societyTitle} Portal`,
    message: `ApniSociety is now active for ${societyTitle}. All dummy test data has been cleared. Committee members can now onboard residents, generate authentic maintenance invoices, and track water and expenses.`,
    category: 'society_notice',
    urgency: 'normal',
    channels: ['in_app', 'push_banner'],
    targetAudience: 'all_residents',
    targetLabel: 'All Residents',
    senderId: primaryAdminMember.id,
    senderName: adminName,
    senderRole: 'General Secretary',
    createdAt: new Date().toISOString(),
    readBy: [],
    isRead: false,
    requiresAcknowledgement: false,
    acknowledgedBy: [],
  };
  localStorage.setItem(STORAGE_KEYS.NOTIFICATIONS, JSON.stringify([welcomeNotification]));

  // 6. Clean Audit Log
  const initialAuditLog = [
    {
      id: `audit-prod-init-${Date.now()}`,
      action: 'PRODUCTION_RESET_AND_INIT',
      performedBy: adminName,
      performedByRole: 'Secretary / Admin',
      timestamp: new Date().toISOString(),
      details: `Application transitioned to Real Production Mode. Purged dummy data, initialized ${realUnits.length} real units, and registered primary administrator.`,
      targetId: 'system_core',
    },
  ];
  localStorage.setItem(STORAGE_KEYS.AUDIT_LOGS, JSON.stringify(initialAuditLog));

  // 7. Fire Global Event
  window.dispatchEvent(new CustomEvent(DATA_RESET_EVENT, { detail: { mode: 'real' } }));

  return {
    success: true,
    message: `Successfully switched to Real Production Mode! Dummy data purged. Created ${realUnits.length} real society units and initialized ${societyTitle}.`,
    generatedUnits: realUnits.length,
  };
}

/**
 * Clear individual module data
 */
export function clearModuleData(
  module:
    | 'maintenance'
    | 'complaints'
    | 'expenses'
    | 'reimbursements'
    | 'water'
    | 'bookings'
    | 'notifications'
    | 'staff'
): void {
  if (typeof window === 'undefined') return;

  switch (module) {
    case 'maintenance':
      localStorage.setItem(STORAGE_KEYS.BILLS, JSON.stringify([]));
      localStorage.setItem(STORAGE_KEYS.DEFAULTERS, JSON.stringify([]));
      break;
    case 'complaints':
      localStorage.setItem(STORAGE_KEYS.COMPLAINTS, JSON.stringify([]));
      break;
    case 'expenses':
      localStorage.setItem(STORAGE_KEYS.EXPENSES, JSON.stringify([]));
      break;
    case 'reimbursements':
      localStorage.setItem(STORAGE_KEYS.CLAIMS, JSON.stringify([]));
      localStorage.setItem(STORAGE_KEYS.DETAILED_CLAIMS, JSON.stringify([]));
      break;
    case 'water':
      localStorage.setItem(STORAGE_KEYS.WATER_READINGS, JSON.stringify([]));
      break;
    case 'bookings':
      localStorage.setItem(STORAGE_KEYS.BOOKINGS, JSON.stringify([]));
      break;
    case 'notifications':
      localStorage.setItem(STORAGE_KEYS.NOTIFICATIONS, JSON.stringify([]));
      break;
    case 'staff':
      localStorage.setItem(STORAGE_KEYS.STAFF, JSON.stringify([]));
      break;
  }

  window.dispatchEvent(new CustomEvent(DATA_RESET_EVENT, { detail: { module } }));
}

/**
 * Restore Demo Test Seed Data (Sandbox mode)
 */
export function restoreDemoData(): void {
  if (typeof window === 'undefined') return;

  localStorage.removeItem(STORAGE_KEYS.DATA_MODE);
  localStorage.removeItem(STORAGE_KEYS.MEMBERS);
  localStorage.removeItem(STORAGE_KEYS.STAFF);
  localStorage.removeItem(STORAGE_KEYS.UNITS);
  localStorage.removeItem(STORAGE_KEYS.BILLS);
  localStorage.removeItem(STORAGE_KEYS.COMPLAINTS);
  localStorage.removeItem(STORAGE_KEYS.EXPENSES);
  localStorage.removeItem(STORAGE_KEYS.CLAIMS);
  localStorage.removeItem(STORAGE_KEYS.DETAILED_CLAIMS);
  localStorage.removeItem(STORAGE_KEYS.WATER_READINGS);
  localStorage.removeItem(STORAGE_KEYS.BOOKINGS);
  localStorage.removeItem(STORAGE_KEYS.NOTIFICATIONS);
  localStorage.removeItem(STORAGE_KEYS.DEFAULTERS);
  localStorage.removeItem(STORAGE_KEYS.ROLES);
  localStorage.removeItem(STORAGE_KEYS.AUDIT_LOGS);

  window.dispatchEvent(new CustomEvent(DATA_RESET_EVENT, { detail: { mode: 'demo' } }));
}

/**
 * Subscribe to data reset and changes
 */
export function subscribeToDataReset(callback: (detail: any) => void): () => void {
  if (typeof window === 'undefined') return () => {};
  const handler = (e: any) => callback(e.detail);
  window.addEventListener(DATA_RESET_EVENT, handler);
  return () => {
    window.removeEventListener(DATA_RESET_EVENT, handler);
  };
}
